spring:
  application:
    name: jwtapp

  security:
    x5u: http://localhost:8000/cert.crt
    private-key: classpath:/key.pem
    passphrase: dGVzdAo=

    # unit: seconds
    jwt-exp: 90
server:
  port: 8080
